### ISSUE TITLE
支持延时加载吗

### ISSUE THREAD

**Issue by transtone** [yangjiyuan/image-placeholder#1]
如题

**Comment by y8n** [comment]
@transtone  你说的延时加载指的是懒加载吧？目前不支持懒加载，因为image-placeholder 无法确定懒加载的时候何时替换src，不过可以通过`placeholder.getBase64Data`生成一个占位符，很多懒加载的框架里都是可以配置的占位符图片地址的，比如[jieyou/lazyload](https://github.com/jieyou/lazyload)这个框架，可以配置`placeholder_data_img`，效果戳→_→ http://plnkr.co/edit/fC74CnJkEfBYJ4PVu2nt?p=preview
